services:
  db:
    image: postgres:16
    container_name: dulcesdb
    environment:
      POSTGRES_DB: dulcesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dulcesdb"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./deploy/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: dulces-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
      TZ: America/Bogota
    ports:
      - "8080:8080"

  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_URL: "/api"
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
